a=int(input("Enter first number:"));
b=int(input("Enter second number:"));
add=a+b;
sub=a-b;
mul=a*b;
dev=a/b;
print("Addition",add);
print("Subtraction",sub);
print("Multiplication",mul);
print("Divition",dev);
